SELECT * FROM TPCDS.INTERMEDIATE.CUSTOMER_SNAPSHOT;

MERGE INTO TPCDS.INTERMEDIATE.CUSTOMER_SNAPSHOT t1
USING TPCDS.RAW.CUSTOMER t2
ON  t1.C_SALUTATION=t2.C_SALUTATION
    AND t1.C_PREFERRED_CUST_FLAG=t2.C_PREFERRED_CUST_FLAG 
    AND coalesce(t1.C_FIRST_SALES_DATE_SK, 0) = coalesce(t2.C_FIRST_SALES_DATE_SK,0) 
    AND t1.C_CUSTOMER_SK=t2.C_CUSTOMER_SK
    AND t1.C_LOGIN=t2.C_LOGIN
    AND coalesce(t1.C_CURRENT_CDEMO_SK,0) = coalesce(t2.C_CURRENT_CDEMO_SK,0)
    AND t1.C_FIRST_NAME=t2.C_FIRST_NAME
    AND coalesce(t1.C_CURRENT_HDEMO_SK,0) = coalesce(t2.C_CURRENT_HDEMO_SK,0)
    AND t1.C_CURRENT_ADDR_SK=t2.C_CURRENT_ADDR_SK
    AND t1.C_LAST_NAME=t2.C_LAST_NAME
    AND t1.C_CUSTOMER_ID=t2.C_CUSTOMER_ID
    AND coalesce(t1.C_LAST_REVIEW_DATE_SK,0) = coalesce(t2.C_LAST_REVIEW_DATE_SK,0)
    AND coalesce(t1.C_BIRTH_MONTH,0) = coalesce(t2.C_BIRTH_MONTH,0)
    AND t1.C_BIRTH_COUNTRY = t2.C_BIRTH_COUNTRY
    AND coalesce(t1.C_BIRTH_YEAR,0) = coalesce(t2.C_BIRTH_YEAR,0)
    AND coalesce(t1.C_BIRTH_DAY,0) = coalesce(t2.C_BIRTH_DAY,0)
    AND t1.C_EMAIL_ADDRESS = t2.C_EMAIL_ADDRESS
    AND coalesce(t1.C_FIRST_SHIPTO_DATE_SK,0) = coalesce(t2.C_FIRST_SHIPTO_DATE_SK,0)
WHEN NOT MATCHED 
THEN INSERT (
    C_SALUTATION, 
    C_PREFERRED_CUST_FLAG, 
    C_FIRST_SALES_DATE_SK, 
    C_CUSTOMER_SK, C_LOGIN, 
    C_CURRENT_CDEMO_SK, 
    C_FIRST_NAME, 
    C_CURRENT_HDEMO_SK, 
    C_CURRENT_ADDR_SK, 
    C_LAST_NAME, 
    C_CUSTOMER_ID, 
    C_LAST_REVIEW_DATE_SK, 
    C_BIRTH_MONTH, 
    C_BIRTH_COUNTRY, 
    C_BIRTH_YEAR, 
    C_BIRTH_DAY, 
    C_EMAIL_ADDRESS, 
    C_FIRST_SHIPTO_DATE_SK,
    START_DATE,
    END_DATE)
VALUES (
    t2.C_SALUTATION, 
    t2.C_PREFERRED_CUST_FLAG, 
    t2.C_FIRST_SALES_DATE_SK, 
    t2.C_CUSTOMER_SK, 
    t2.C_LOGIN, 
    t2.C_CURRENT_CDEMO_SK, 
    t2.C_FIRST_NAME, 
    t2.C_CURRENT_HDEMO_SK, 
    t2.C_CURRENT_ADDR_SK, 
    t2.C_LAST_NAME, 
    t2.C_CUSTOMER_ID, 
    t2.C_LAST_REVIEW_DATE_SK, 
    t2.C_BIRTH_MONTH, 
    t2.C_BIRTH_COUNTRY, 
    t2.C_BIRTH_YEAR, 
    t2.C_BIRTH_DAY, 
    t2.C_EMAIL_ADDRESS, 
    t2.C_FIRST_SHIPTO_DATE_SK,
    CURRENT_DATE(),
    NULL
);

SELECT * FROM TPCDS.INTERMEDIATE.CUSTOMER_SNAPSHOT;

MERGE INTO TPCDS.INTERMEDIATE.CUSTOMER_SNAPSHOT t1
USING TPCDS.RAW.CUSTOMER t2
ON  t1.C_CUSTOMER_SK=t2.C_CUSTOMER_SK
WHEN MATCHED
    AND (
    t1.C_SALUTATION!=t2.C_SALUTATION
    OR t1.C_PREFERRED_CUST_FLAG!=t2.C_PREFERRED_CUST_FLAG 
    OR coalesce(t1.C_FIRST_SALES_DATE_SK, 0) != coalesce(t2.C_FIRST_SALES_DATE_SK,0) 
    OR t1.C_LOGIN!=t2.C_LOGIN
    OR coalesce(t1.C_CURRENT_CDEMO_SK,0) != coalesce(t2.C_CURRENT_CDEMO_SK,0)
    OR t1.C_FIRST_NAME!=t2.C_FIRST_NAME
    OR coalesce(t1.C_CURRENT_HDEMO_SK,0) != coalesce(t2.C_CURRENT_HDEMO_SK,0)
    OR t1.C_CURRENT_ADDR_SK!=t2.C_CURRENT_ADDR_SK
    OR t1.C_LAST_NAME!=t2.C_LAST_NAME
    OR t1.C_CUSTOMER_ID!=t2.C_CUSTOMER_ID
    OR coalesce(t1.C_LAST_REVIEW_DATE_SK,0) != coalesce(t2.C_LAST_REVIEW_DATE_SK,0)
    OR coalesce(t1.C_BIRTH_MONTH,0) != coalesce(t2.C_BIRTH_MONTH,0)
    OR t1.C_BIRTH_COUNTRY != t2.C_BIRTH_COUNTRY
    OR coalesce(t1.C_BIRTH_YEAR,0) != coalesce(t2.C_BIRTH_YEAR,0)
    OR coalesce(t1.C_BIRTH_DAY,0) != coalesce(t2.C_BIRTH_DAY,0)
    OR t1.C_EMAIL_ADDRESS != t2.C_EMAIL_ADDRESS
    OR coalesce(t1.C_FIRST_SHIPTO_DATE_SK,0) != coalesce(t2.C_FIRST_SHIPTO_DATE_SK,0)
    ) 
THEN UPDATE SET
    end_date = current_date();


create or replace table TPCDS.ANALYTICS.CUSTOMER_DIM as
        (select 
        C_SALUTATION as SALUTATION,
        C_PREFERRED_CUST_FLAG as PREFERRED_CUST_FLAG,
        C_FIRST_SALES_DATE_SK as FIRST_SALES_DATE_SK,
        C_CUSTOMER_SK as CUSTOMER_SK,
        C_LOGIN as LOGIN,
        C_CURRENT_CDEMO_SK as CURRENT_CDEMO_SK,
        C_FIRST_NAME as FIRST_NAME,
        C_CURRENT_HDEMO_SK as CURRENT_HDEMO_SK,
        C_CURRENT_ADDR_SK as CURRENT_ADDR_SK,
        C_LAST_NAME as LAST_NAME,
        C_CUSTOMER_ID as CUSTOMER_ID,
        C_LAST_REVIEW_DATE_SK as LAST_REVIEW_DATE_SK,
        C_BIRTH_MONTH as BIRTH_MONTH,
        C_BIRTH_COUNTRY as BIRTH_COUNTRY,
        C_BIRTH_YEAR as BIRTH_YEAR,
        C_BIRTH_DAY as BIRTH_DAY,
        C_EMAIL_ADDRESS as EMAIL_ADDRESS,
        C_FIRST_SHIPTO_DATE_SK as FIRST_SHIPTO_DATE_SK,
        CA_STREET_NAME as STREET_NAME,
        CA_SUITE_NUMBER as SUITE_NUMBER,
        CA_STATE as STATE,
        CA_LOCATION_TYPE as LOCATION_TYPE,
        CA_COUNTRY as COUNTRY,
        CA_ADDRESS_ID as ADDRESS_ID,
        CA_COUNTY as COUNTY,
        CA_STREET_NUMBER as STREET_NUMBER,
        CA_ZIP as ZIP,
        CA_CITY as CITY,
        CA_GMT_OFFSET as GMT_OFFSET,
        CD_DEP_EMPLOYED_COUNT as DEP_EMPLOYED_COUNT,
        CD_DEP_COUNT,
        CD_CREDIT_RATING as CREDIT_RATING,
        CD_EDUCATION_STATUS as EDUCATION_STATUS,
        CD_PURCHASE_ESTIMATE as PURCHASE_ESTIMATE,
        CD_MARITAL_STATUS as MARITAL_STATUS,
        CD_DEP_COLLEGE_COUNT as DEP_COLLEGE_COUNT,
        CD_GENDER as GENDER,
        HD_BUY_POTENTIAL as BUY_POTENTIAL,
        HD_DEP_COUNT,
        HD_VEHICLE_COUNT as VEHICLE_COUNT,
        HD_INCOME_BAND_SK as INCOME_BAND_SK,
        IB_LOWER_BOUND as INCOME_BAND_LOWER_BOUND,
        IB_UPPER_BOUND as INCOME_BAND_UPPER_BOUND,
        START_DATE,
        END_DATE
from TPCDS.INTERMEDIATE.CUSTOMER_SNAPSHOT
LEFT JOIN TPCDS.RAW.CUSTOMER_ADDRESS ON C_CURRENT_ADDR_SK = CA_ADDRESS_SK
LEFT JOIN TPCDS.RAW.CUSTOMER_DEMOGRAPHICS ON C_CURRENT_CDEMO_SK = CD_DEMO_SK
LEFT JOIN TPCDS.RAW.HOUSEHOLD_DEMOGRAPHICS ON C_CURRENT_HDEMO_SK = HD_DEMO_SK
LEFT JOIN TPCDS.RAW.INCOME_BAND ON HD_INCOME_BAND_SK = IB_INCOME_BAND_SK
where end_date is null
        );

-- Showing cases where C_FIRST_SALES_DATE_SK is null

select count(*) from TPCDS.RAW.CUSTOMER where C_FIRST_SALES_DATE_SK is null; --3518 records