-- Getting Last Date
SET LAST_PURCHASE_WK_SK = (SELECT MAX(PURCHASE_WK_SK) FROM TPCDS.ANALYTICS.WEEKLY_CUSTOMER_COUNT);

-- Removing partial records from the last date
DELETE FROM TPCDS.ANALYTICS.WEEKLY_CUSTOMER_COUNT WHERE PURCHASE_WK_SK=$LAST_PURCHASE_WK_SK;

-- compiling all incremental sales records
CREATE OR REPLACE TEMPORARY TABLE TPCDS.ANALYTICS.WEEKLY_CUSTOMER_COUNT_TMP AS (
with aggregating_daily_customers_by_week as (
SELECT 
    MIN(PURCHASE_DATE_SK) AS PURCHASE_WK_SK, 
    PURCHASE_WK_NUM, 
    PURCHASE_YR_NUM, 
    COUNT(DISTINCT (CASE WHEN CATALOG_PURCHASE = TRUE THEN CUSTOMER_SK END)) AS CATALOG_CUSTOMERS_WK, 
    COUNT(DISTINCT (CASE WHEN WEB_PURCHASE = TRUE THEN CUSTOMER_SK END)) AS WEB_CUSTOMERS_WK
FROM
    TPCDS.INTERMEDIATE.DAILY_CUSTOMERS
GROUP BY
    2,3
HAVING 
    PURCHASE_WK_SK >= NVL($LAST_PURCHASE_WK_SK,0)
)

SELECT 
    date.d_date_sk AS PURCHASE_WK_SK, 
    PURCHASE_WK_NUM, 
    PURCHASE_YR_NUM,
    CATALOG_CUSTOMERS_WK,
    WEB_CUSTOMERS_WK 
FROM
    aggregating_daily_customers_by_week daily_customers
INNER JOIN TPCDS.RAW.DATE_DIM as date
on daily_customers.PURCHASE_WK_NUM=date.wk_num
and daily_customers.PURCHASE_YR_NUM=date.yr_num
and date.day_of_wk_num=0
);

-- Inserting new records
INSERT INTO TPCDS.ANALYTICS.WEEKLY_CUSTOMER_COUNT
(	
	PURCHASE_WK_SK, 
    PURCHASE_WK_NUM, 
    PURCHASE_YR_NUM,
    CATALOG_CUSTOMERS_WK,
    WEB_CUSTOMERS_WK 
)
SELECT 
    PURCHASE_WK_SK, 
    PURCHASE_WK_NUM, 
    PURCHASE_YR_NUM,
    CATALOG_CUSTOMERS_WK,
    WEB_CUSTOMERS_WK 
FROM TPCDS.ANALYTICS.WEEKLY_CUSTOMER_COUNT_TMP;