[sf]
warehouse = "COMPUTE_WH"
database = "TPCDS"
schema = "RAW"
role = "ACCOUNTADMIN"
file_format_name = "CSV_FORMAT"
stage_name = "INVENTORY_STAGE"
table = "INVENTORY"

[data]
url="https://de-materials-tpcds.s3.ca-central-1.amazonaws.com/inventory.csv"
dest_folder = "/tmp"
file_name = "inventory.csv"